/**
 * @Name: AbstractclassImplementor 
 * @Description: it does not contain any method defination, methods to be override later.
 * @Author: Kanika Gurditta
 **/
 public class AbstractclassImplementor extends Abstractclass {  
 
     /**
     * @Description: override from Abstractclass .
     * @Author: Kanika Gurditta
     * @Date: 10-08-2017
     * @Return: void
     **/
      
   public override void  methodX(){
   
   System.debug('***you are in methodX');
   
   }//end methodX
   
   /**
     * @Description: override from Abstractclass .
     * @Author: Kanika Gurditta
     * @Date: 10-08-2017
     * @Return: void
    **/
   
   public override void methodY(){
   System.debug('***you are in methodY');  
    }//end methodY  

}//end AbstractclassImplementor