/**
 * @Name: Abstractclass 
 * @Description: it does not contain any method defination, methods to be override later.
 * @Author: Kanika Gurditta
 **/

 public abstract class Abstractclass {
   /**
     * @Description: method to be override by AbstractclassImplementor .
     * @Author: Kanika Gurditta
     * @Date: 10-08-2017
     * @Return: void
   **/  
     
   public abstract void methodX();
   public abstract void methodY();
 }//end Abstractclass